name: Call a reusable workflow

on: ['push']

jobs:
  foobar:
    strategy:
      matrix:
        target: [foo, bar]
    uses: ./.github/workflows/call-foo-bar.yml
    with:
      value: ${{ matrix.target }}

  foo:
    needs: foobar
    uses: ./.github/workflows/bar.yml

  bar:
    needs: foobar
    uses: ./.github/workflows/foo.yml
